# .github/workflows/tagpr.yml
name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: Songmu/tagpr@main
      - name: log
        shell: bash
        run: |
          echo "tag: ${{ steps.tagpr.outputs.tag }}"
      - name: release
        if: ${{ steps.tagpr.outputs.tag != '' }}
        shell: bash
        run: |
          echo ":rocket: Release ${{ steps.tagpr.outputs.tag }}"