on: 
  push:
  pull_request:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo "$GITHUB_REF"
          version="${GITHUB_REF#refs/tags/}"
          echo "$version"
          branches="${GITHUB_REF#refs/branches/}"
          echo "$branches"