on: 
  push:
  pull_request:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo "1: $GITHUB_REF"
          version="${GITHUB_REF#refs/tags/}"
          echo "2: $version"
          branches="${GITHUB_REF#refs/branches/}"
          echo "3: $branches"