name: test2
on:
  push:
    branches:
      - main
    tags:
      - "v.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: "release tag"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: tag
        id: tag
        # inputs.tagがなかったらgithub.refから取得する(v1.0.0の形式)
        run: |
          if [ -z "${{ inputs.tag }}" ]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${{ inputs.tag }}" >> "$GITHUB_OUTPUT"
          fi
      - name: out
        run: |
          tag="${{ steps.tag.outputs.tag }}"
          version=${tag#v}
          echo "1: $version"
          test="$version-SNAPSHOT"
          echo "2: $test"